# Generated by Django 4.0.4 on 2023-07-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.FileField(upload_to='pics/'),
        ),
    ]
