# Generated by Django 4.0.4 on 2023-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects02', '0002_alter_projectimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(blank=True, path='/static'),
        ),
    ]
