# Generated by Django 4.0.4 on 2023-07-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects02', '0006_remove_project_description_remove_project_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description_de',
            new_name='beschreibung',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description_en',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title_de',
            new_name='titel',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title_en',
            new_name='title',
        ),
    ]
