# Generated by Django 4.0.4 on 2023-07-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects02', '0007_rename_description_de_project_beschreibung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kurzbeschreibung',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
