# Generated by Django 4.2.3 on 2023-07-23 06:03

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects02', '0009_alter_project_beschreibung_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('video', embed_video.fields.EmbedVideoField(blank=True, default=None)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects02.project')),
            ],
        ),
    ]
