# Generated by Django 4.2.3 on 2023-07-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects02', '0010_projectvideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectVideo',
            new_name='ProjectEmbed',
        ),
    ]
