# Generated by Django 4.2.3 on 2023-07-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects02', '0012_project_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='embed',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
