# Generated by Django 4.0.4 on 2023-07-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects02', '0014_alter_projectembed_options_projectembed_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.CharField(blank=True, choices=[('Y', 'YES'), ('N', 'NO')], max_length=10),
        ),
    ]
