# Generated by Django 4.0.4 on 2023-07-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects02', '0015_project_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='credit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
