# Generated by Django 4.0.4 on 2023-07-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects02', '0016_projectimage_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='images',
            new_name='image',
        ),
    ]
